language: swift
osx_image: xcode8.3
cache:
- bundler
before_install:
- bundle install
- bundle update
- npm install -g cordova ionic
- npm install
script:
- fastlane beta
env:
  global:
  - secure: KtrtZMDXBQwcsyhIBJUh8q2uR1bFJ10HA8hDUktB+X8vTP63W7DnfwiacvUh38lRfHH7aGtlaKHXv7x9vVb2X79opTeWTeoWMPJ394m6+MZAv4yB2+WNR2a0kG5mLNrhPwvMNNqZbXyl5HNJ+CzLT7gLwUj3y+IFzQOUNwwlX3RKRag8goOKHikea3cEVbpAaaJDz8IJG1L/DrxAxIDuU2dAwpEw9y0doHYy2B98RR3srNDrh4/uLjRQRuBHd9SDpvRUTd2sL4QEeUnBA7QqWid9FMDRwhr5tD40pnHDcperYzZrB/CLzwr6ZWEe5/GDrFNQDi1czT5Gy41aiqUz87j8Vc+uFX9dw+0jBX9Xoe1SyUXBnw3IN7JiSquyH9sWtgaG8QvN9x6RjBtWT1wEq3HECooujNvjXCMBI4aoxQiMzIKOHA+ZG6R8RL0Y9KElAnW+JLqqjB2lxqp0qyFOjpWuGRYWCgSSdFODGfofu1BR+ZHJxAFSpYN6PcSdCJEZ9K1eo6hl0M6nPVDrbUWDVdu3SWYz71uZD4mfFR9BauKg4z/I3EM33SaS+YRG1ZVTcmfnv9esgjFaCb0qe1SMsC9oRVpi9io5Mh/iTcN80lhCv1JX21Mgf7hYas2srVmLs8PCUf1gz+OHz3/+DO1HnJwlB1jPYgRYjcdKbbWXNe0=
  - secure: NxnZp3aKD0tS+QhbKHvy1CdXC1/HPUs+cb0yI0ypPDXPznirwmm6IlSAC6vUbRxRForcj2t9TU/6LwMJ1JnZxbhtvTdm2qh3HaOjspCebKUvK06P1KFqH/DMV6z+Vb16rdV29uF14sm6kVz5qgsP6wK1jHwNg4FJUIDNLmdyM2gmmKb2FD29TS6C2hcUD66AiWuGHZMeMxwezvTNv/uKTyCCPjerYJ6QOv50tzWBApmgPvzLvkUNZaP1LGc02Q1sIHwJexMFzVHlLXv1sFmePlb9nw9crT9V58ga9A8tx6ooE2qYLAITw/CIIapptWOiDonYm16qdUeT/qHicB92xIxjsj8gMn52pBvsijLiwaYXK9FMWQT7GrFD9XDZtx0JAG+gIsn68shptjEPqWLA0ZdluLI98hjDPj48agU69SJsv4cDvgHqmzCLLEkY7juq3JZyWhcPTYrQC6x4HJzD0vL/GwSVkRkECIkvPmSqwF1JQ360dxShFfZaa+nxwTqHJrSdSaEQgCuQhN6hIlYe3x45ItHcDRDRgPfXFg5FvfocjsAxro4x8ELSHKNGxhBlQGyJMfUaBuiiLXsYK22flQzV1iWhJmJiQL4+i5T9LlLZwfPWUpmgy3XUHntm5iSCjQ5jHmUTgVOhsdc4Fz6quQK6RlrAyj7MTPlmgaG3bPo=
